### ISSUE TITLE
how to debug adapter macros?

### ISSUE THREAD

**Issue by swanderz** [mikaelene/dbt-sqlserver#23]
full disclosure: total newb post

I'm trying to adapt your adapter to `azure-synapse`, I'm getting (and expecting errors), but I'm unsure how to isolate which macros I need to tweak. For me this is where I attach a debugger and step through the process, but I'm definitely missing some skills and context.

Originally, I was getting an error related to `sp_rename` which makes sense as the sproc isn't supported in Synapse. So I CMD+F for `sp_rename` and find the `sqlserver__rename_relation` macro, which I tweak to use the Synapse-supported `RENAME OBJECT` syntax.

For example, I'm trying to create a simple view with zero jinja in it (for simplicity's sake).

But now I'm getting the following error, which is troubling, because the sql compiled at `stage/stg_headcount.sql` works without issue. It must be another macro, no?

### error (`\n` added for clarity)

[here's the full log w/ stacktrace](https://gist.github.com/swanderz/8458d5374bdf188771b25565c2ea8073)
```
> dbt run --target sqlserver --model stg_headcount
('42000', "[42000]
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
Parse error at line: 1, column: 15:
Incorrect syntax near ''source.stg_headcount__dbt_tmp''. (103010) (SQLExecDirectW)")
compiled SQL at target/run/ava_its_data/stage/stg_headcount.sql
```

### `stg_headcount.sql`
```sql
SELECT
    MonthCode
    ,CountryNm
    ,Total_Employees
FROM "may_test_sqlpool"."source"."monthly_headcount"
```

### `stg_schema.yml`
```yaml
version: 2

models:
  - name: stg_headcount
    description: >
      demo table for debugging
    columns:
      - name: MonthCode
      - name: CountryNm
      - name: Total_Employees

```

### `stage/stg_headcount.sql`

```sql
create view source.stg_headcount__dbt_tmp as
    SELECT
    MonthCode
    ,CountryNm
    ,Total_Employees
FROM "may_test_sqlpool"."source"."monthly_headcount"
```
