### ISSUE TITLE
Add support for sql server named instance

### ISSUE THREAD

**Issue by alangsbo** [mikaelene/dbt-sqlserver#50]
If sql server host name contains a backslash - pointing at a named instance connection to server fails

This is because if a named instance is specified, the port number must be omitted.

This can be fixed by replacing row 90 in connections.py with this code:

```
if "\\" in credentials.host:
                # if there is a backslash \ in the host name the host is a sql-server named instance
                # in this case then port number has to be omitted
                con_str.append(f"SERVER={credentials.host}")
            else:
                con_str.append(f"SERVER={credentials.host},{credentials.port}")
```

Maybe there is a more elegant way to do it, but the above works for me :)

**Comment by mikaelene** [comment]
Thanks for the example! Have you tested this for a non-instance of SQL Server so the original functionality still works? Mind submitting a pull request?

**Comment by alangsbo** [comment]
Good suggestion, I have tested a default instance also.

I´ll submit a pull req

**Comment by mikaelene** [comment]
Solved by #51

**Comment by codeforkjeff** [comment]
For anyone trying to connect to a default instance: a trailing backslash seems to work. This target defined in `~/.dbt/profiles.yml` works for me: 

```YAML
my_project:

  outputs:

    dev:
      type: sqlserver
      driver: 'SQL Server Native Client 11.0'
      host: localhost\
      database: mydatabase
      schema: dbo
      windows_login: True

  target: dev
```

Note that a string like ` localhost\MSSQLSERVER` (which is supposedly the name of the default instance) did NOT work for me. I'm running SQL Server 2016.
